---

  -  name: make sure epel is enabled
     yum:
       name: epel-release
       state: present

  -  name: install fail2ban
     yum:
       name: fail2ban
       state: latest



  -  name: copy fail2ban config to local
     template:
       src: jail.local.j2
       dest: /etc/fail2ban/jail.local
       owner: root
       group: root
       mode: 0644

  -  name: fail2ban enable and start
     service:
       name: fail2ban
       state: started
       enabled: true
