---

       -  name: add ansible user and grp
          user:
            name: "{{ username }}"
            password: "{{ passwd | password_hash('sha512') }}"
            state: present
       -  name: config sudoers
          copy:
            content: " %ansible ALL=(ALL) NOPASSWD: ALL"
            dest: /etc/sudoers.d/ansible

       -  name: sets sshd keys
          authorized_key:
            user: "{{ username }}"
            state: present
            key: "{{ lookup('file','/home/ansible/.ssh/id_rsa.pub') }}"
       -  name: sshd restart
          service:
            name: sshd
            state: restarted
