
---

       -  name: add docker repo
          yum_repository:
            name: "{{ docker_repo_name }}"
            description: docker-repo
            file: docker
            baseurl: "{{ docker_url }}"
            gpgcheck: no

       -  name: install docker
          command: "yum install docker-ce --allowerasing -y"

       -  name: start and enable docker service
          service:
            name: "{{ docker_service }}"
            state: started
            enabled: true
          become: yes

       -  name: install docker sdk for python
          command: "pip3 install docker-py"
